### ISSUE TITLE
Some videos don't load

### ISSUE THREAD

**Issue by sydia1103** [ciulinuwu/ciulin-s-youtube#22]
Some videos, such as this [CBC Marketplace](https://www.youtube.com/watch?v=Gdc9_uPETIE) video, doesn't work for some reason. In console it shows, `undefined has no properties` as an error. It seems there is something undefined that is causing your entire script to crash on the video and not load anything.

**Comment by ciulinuwu** [comment]
Hi. I can't seem to replicate most of the issue. I have a few questions that might help sorting things out.

1. How fast is your Internet? (mbps)
2. Do you have Adblock Plus?
3. Does the issue occur randomly on that video or does it occur every time?

I found some render issues with Chrome after disabling/using Adblock. ABP (Adblock Plus) seemed to work better, but I don't know if that's relevant. Please let me know.

**Comment by sydia1103** [comment]
My internet is 300 MBPS, I have normal Adblock from the Chrome webstore. Yes, the issue occurs every single time on that video.

**Comment by ciulinuwu** [comment]
Okay. So I have no idea how to fix it. I am getting issues with Chrome on that specific video where both layouts render at the same time. Can you try using the script with Firefox? It's not broken there for me.

**Comment by ciulinuwu** [comment]
Closed due to incompatibility with Chromium. Please use Mozilla Firefox to use the script.

**Comment by sydia1103** [comment]
The video above still refuses to play on Firefox 78.15 with 2 errors. They are as follows: `Uncaught (in promise) ReferenceError: ytInitialData is not defined` and `Uncaught Error: Could not find root selector ytd-app`

**Comment by ciulinuwu** [comment]
@sydia1103 Try the latest version of Firefox. 102.0.1 It might be because of an old version.

**Comment by sydia1103** [comment]
@ciulinuwu 
I tried that and still get a blank page but a different error. `Uncaught (in promise) TypeError: undefined has no properties`. Try switching accounts and clearing cookies to see if you can replicate the error.

**Comment by ciulinuwu** [comment]
Where does the error come from?

I tried. But everything seems fine to me.

**Comment by sydia1103** [comment]
@ciulinuwu The error comes from the console and your script. `FUNC moz-extension://73931ed0-31c4-46a7-93dc-da4e5ae0573f/userscripts/Ciulin's YouTube.user.js?id=d0410f66-ced0-4ec2-a28b-91000a6523ef:2452`

**Comment by ciulinuwu** [comment]
Can you click on the error and send me a screenshot of where it sends you? UserScripts gets loaded with extra stuff on the top so it'd be hard to pinpoint the exact line.

**Comment by sydia1103** [comment]
It lands on the following line. 
![Uploading Screen Shot 2022-07-09 at 5.01.59 PM.png…]()

**Comment by ciulinuwu** [comment]
Alright. Can you please install this version of the script and let me out what it outputs in the Console as Debug (Make sure Debug is toggled)
https://github.com/ciulinuwu/ciulin-s-youtube/raw/test-organizeVideoData/Ciulin's%20YouTube.user.js

**Comment by sydia1103** [comment]
It outputs a debug result containing compactLinkRenderer. `Object { compactLinkRenderer: {…} }
​
compactLinkRenderer: Object { icon: {…}, title: {…}, trackingParams: "CN0BEMCeCRgAIhMI0uSun6zu-AIVE8PCBB2gqQiI", … }
​​
icon: Object { iconType: "ACCOUNT_BOX" }
​​​
iconType: "ACCOUNT_BOX"
​​​
<prototype>: Object { … }
​​
navigationEndpoint: Object { clickTrackingParams: "CN0BEMCeCRgAIhMI0uSun6zu-AIVE8PCBB2gqQiI", commandMetadata: {…}, browseEndpoint: {…} }
​​​
browseEndpoint: Object { browseId: "UCdrJcV_wvd-vg4rCVAomxrw" }
​​​
clickTrackingParams: "CN0BEMCeCRgAIhMI0uSun6zu-AIVE8PCBB2gqQiI"
​​​
commandMetadata: Object { webCommandMetadata: {…} }
​​​
<prototype>: Object { … }
​​
title: Object { runs: (1) […] }
​​
trackingParams: "CN0BEMCeCRgAIhMI0uSun6zu-AIVE8PCBB2gqQiI"
​​
<prototype>: Object { … }
​
<prototype>: Object { … }
Ciulin's YouTube.user.js:2280:25
`
Most of it isn't expanded, tell me if you need me to expand it.

**Comment by ciulinuwu** [comment]
Hmm. Hold on I uploaded a new version, can you please use that instead and tell me the console output?

**Comment by ciulinuwu** [comment]
Hmm. That doesn't seem right... Can you try the version I just uploaded now? I think it came out of the wrong debugger.

**Comment by sydia1103** [comment]
Which branch is that? I tried the one you uploaded in the test-OrganizeVideoData branch, but it outputs no debug.

**Comment by ciulinuwu** [comment]
OH CRAP wait!

**Comment by ciulinuwu** [comment]
Okay try again! Branch: test-organizeVideoData

**Comment by sydia1103** [comment]
I get the following.`Object { contents: (5) […], trackingParams: "CNwCELovIhMIn8Wruubu-AIVDNLECh1RqgOi" }
​
contents: Array(5) [ {…}, {…}, {…}, … ]
​​
0: Object { itemSectionRenderer: {…} }
​​​
itemSectionRenderer: Object { contents: (1) […], trackingParams: "CPcCELsvGAAiEwifxau65u74AhUM0sQKHVGqA6I=" }
​​​​
contents: Array [ {…} ]
​​​​​
0: Object { infoPanelContentRenderer: {…} }
​​​​​​
infoPanelContentRenderer: Object { inlineLinkIcon: {…}, trackingParams: "CPgCEMChAhgAIhMIn8Wruubu-AIVDNLECh1RqgOi", background: "INFO_PANEL_CONTENT_BACKGROUND_BLUE", … }
​​​​​​​
background: "INFO_PANEL_CONTENT_BACKGROUND_BLUE"
​​​​​​​
inlineLinkIcon: Object { iconType: "OPEN_IN_NEW" }
​​​​​​​
inlineSource: Object { runs: (1) […] }
​​​​​​​
loggingDirectives: Object { trackingParams: "CPgCEMChAhgAIhMIn8Wruubu-AIVDNLECh1RqgOi", visibility: {…}, enableDisplayloggerExperiment: true, … }
​​​​​​​
menu: Object { menuRenderer: {…} }
​​​​​​​
paragraphs: Array [ {…} ]
​​​​​​​
sourceEndpoint: Object { clickTrackingParams: "CPgCEMChAhgAIhMIn8Wruubu-AIVDNLECh1RqgOi", commandMetadata: {…}, urlEndpoint: {…} }
​​​​​​​
trackingParams: "CPgCEMChAhgAIhMIn8Wruubu-AIVDNLECh1RqgOi"
​​​​​​​
<prototype>: Object { … }
​​​​​​
<prototype>: Object { … }
​​​​​
length: 1
​​​​​
<prototype>: Array []
​​​​
trackingParams: "CPcCELsvGAAiEwifxau65u74AhUM0sQKHVGqA6I="
​​​​
<prototype>: Object { … }
​​​
<prototype>: Object { … }
​​
1: Object { videoPrimaryInfoRenderer: {…} }
​​​
videoPrimaryInfoRenderer: Object { title: {…}, viewCount: {…}, trackingParams: "CPACEMyrARgBIhMIn8Wruubu-AIVDNLECh1RqgOi", … }
​​​​
dateText: Object { simpleText: "Oct 8, 2021" }
​​​​
superTitleIcon: Object { iconType: "LOCATION_PIN" }
​​​​
superTitleLink: Object { runs: (1) […], accessibility: {…} }
​​​​
title: Object { runs: (1) […] }
​​​​
trackingParams: "CPACEMyrARgBIhMIn8Wruubu-AIVDNLECh1RqgOi"
​​​​
videoActions: Object { menuRenderer: {…} }
​​​​
viewCount: Object { videoViewCountRenderer: {…} }
​​​​
<prototype>: Object { … }
​​​
<prototype>: Object { … }
​​
2: Object { videoSecondaryInfoRenderer: {…} }
​​​
videoSecondaryInfoRenderer: Object { trackingParams: "COACEM2rARgCIhMIn8Wruubu-AIVDNLECh1RqgOi", defaultExpanded: false, descriptionCollapsedLines: 3, … }
​​​​
defaultExpanded: false
​​​​
description: Object { runs: (27) […] }
​​​​
descriptionCollapsedLines: 3
​​​​
metadataRowContainer: Object { metadataRowContainerRenderer: {…} }
​​​​
owner: Object { videoOwnerRenderer: {…} }
​​​​
showLessCommand: Object { clickTrackingParams: "COACEM2rARgCIhMIn8Wruubu-AIVDNLECh1RqgOi", changeEngagementPanelVisibilityAction: {…} }
​​​​
showLessText: Object { simpleText: "Show less" }
​​​​
showMoreCommand: Object { clickTrackingParams: "COACEM2rARgCIhMIn8Wruubu-AIVDNLECh1RqgOi", commandExecutorCommand: {…} }
​​​​
showMoreText: Object { simpleText: "Show more" }
​​​​
subscribeButton: Object { subscribeButtonRenderer: {…} }
​​​​
trackingParams: "COACEM2rARgCIhMIn8Wruubu-AIVDNLECh1RqgOi"
​​​​
<prototype>: Object { … }
​​​
<prototype>: Object { … }
​​
3: Object { itemSectionRenderer: {…} }
​​​
itemSectionRenderer: Object { contents: (1) […], trackingParams: "CN4CELsvGAMiEwifxau65u74AhUM0sQKHVGqA6I=", sectionIdentifier: "comments-entry-point" }
​​​​
contents: Array [ {…} ]
​​​​​
0: Object { commentsEntryPointHeaderRenderer: {…} }
​​​​​​
commentsEntryPointHeaderRenderer: Object { headerText: {…}, trackingParams: "CN8CEMTgBBgAIhMIn8Wruubu-AIVDNLECh1RqgOi", targetId: "comments-entry-point-header-identifier", … }
​​​​​​​
commentCount: Object { simpleText: "3.2K" }
​​​​​​​​
simpleText: "3.2K"
​​​​​​​​
<prototype>: Object { … }
​​​​​​​
headerText: Object { runs: (1) […] }
​​​​​​​
onTap: Object { clickTrackingParams: "CN8CEMTgBBgAIhMIn8Wruubu-AIVDNLECh1RqgOi", commandExecutorCommand: {…} }
​​​​​​​
simpleboxAvatar: Object { thumbnails: (3) […], accessibility: {…} }
​​​​​​​
simpleboxPlaceholder: Object { runs: (1) […] }
​​​​​​​
targetId: "comments-entry-point-header-identifier"
​​​​​​​
trackingParams: "CN8CEMTgBBgAIhMIn8Wruubu-AIVDNLECh1RqgOi"
​​​​​​​
<prototype>: Object { … }
​​​​​​
<prototype>: Object { … }
​​​​​
length: 1
​​​​​
<prototype>: Array []
​​​​
sectionIdentifier: "comments-entry-point"
​​​​
trackingParams: "CN4CELsvGAMiEwifxau65u74AhUM0sQKHVGqA6I="
​​​​
<prototype>: Object { … }
​​​
<prototype>: Object { … }
​​
4: Object { itemSectionRenderer: {…} }
​​​
itemSectionRenderer: Object { trackingParams: "CN0CELsvGAQiEwifxau65u74AhUM0sQKHVGqA6I=", sectionIdentifier: "comment-item-section", targetId: "comments-section", … }
​​​​
contents: Array [ {…} ]
​​​​​
0: Object { continuationItemRenderer: {…} }
​​​​​​
continuationItemRenderer: Object { trigger: "CONTINUATION_TRIGGER_ON_ITEM_SHOWN", continuationEndpoint: {…} }
​​​​​​​
continuationEndpoint: Object { clickTrackingParams: "CN0CELsvGAQiEwifxau65u74AhUM0sQKHVGqA6I=", commandMetadata: {…}, continuationCommand: {…} }
​​​​​​​​
clickTrackingParams: "CN0CELsvGAQiEwifxau65u74AhUM0sQKHVGqA6I="
​​​​​​​​
commandMetadata: Object { webCommandMetadata: {…} }
​​​​​​​​
continuationCommand: Object { token: "Eg0SC0dkYzlfdVBFVElFGAYyJSIRIgtHZGM5X3VQRVRJRTAAeAJCEGNvbW1lbnRzLXNlY3Rpb24%3D", request: "CONTINUATION_REQUEST_TYPE_WATCH_NEXT" }
​​​​​​​​​
request: "CONTINUATION_REQUEST_TYPE_WATCH_NEXT"
​​​​​​​​​
token: "Eg0SC0dkYzlfdVBFVElFGAYyJSIRIgtHZGM5X3VQRVRJRTAAeAJCEGNvbW1lbnRzLXNlY3Rpb24%3D"
​​​​​​​​​
<prototype>: Object { … }
​​​​​​​​
<prototype>: Object { … }
​​​​​​​
trigger: "CONTINUATION_TRIGGER_ON_ITEM_SHOWN"
​​​​​​​
<prototype>: Object { … }
​​​​​​
<prototype>: Object { … }
​​​​​
length: 1
​​​​​
<prototype>: Array []
​​​​
sectionIdentifier: "comment-item-section"
​​​​
targetId: "comments-section"
​​​​
trackingParams: "CN0CELsvGAQiEwifxau65u74AhUM0sQKHVGqA6I="
​​​​
<prototype>: Object { … }
​​​
<prototype>: Object { … }
​​
length: 5
​​
<prototype>: Array []
​
trackingParams: "CNwCELovIhMIn8Wruubu-AIVDNLECh1RqgOi"
​
<prototype>: Object { … }
Ciulin's YouTube.user.js:2458:29
` Hope this helps.

**Comment by ciulinuwu** [comment]
It appears the Arrays has rearranged for some reason. I've pushed a new upload. Let me know if it continues!

**Comment by sydia1103** [comment]
It still continues, this time it spits out a more detailed error of, `Uncaught (in promise) TypeError: ytInitialData.contents.twoColumnWatchNextResults.results.results.contents[0].videoPrimaryInfoRenderer is undefined` Hopefully this helps.

**Comment by ciulinuwu** [comment]
ahh. Okay pushed another update.

**Comment by sydia1103** [comment]
This time, it spits out a slightly different error of, `Uncaught (in promise) TypeError: ytInitialData.contents.twoColumnWatchNextResults.results.results.contents[1].videoSecondaryInfoRenderer is undefined`. Hope this helps fix this issue.

**Comment by ciulinuwu** [comment]
Sure does! I think it should be fixed now!

**Comment by sydia1103** [comment]
Yep, that fixed it. Thanks for your hard work trying to solve this issue! Closed.
